import type { Metadata } from "next";
import { Inter, Poppins, Nunito_Sans } from "next/font/google";
import "./globals.css";
import MainNav from "./ui/mainNav";


const inter = Inter({
  variable: '--font-inter',
  subsets: ["latin"],
})

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ["latin"],
  weight: "300"
})

const nunitoSans = Nunito_Sans({
  variable: '--font-nunitoSans',
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col justify-center ${inter.variable} ${poppins.variable} ${nunitoSans.variable} antialiased`}
      >
        <MainNav />
        {children}
      </body>
    </html>
  );
}
